version: "3.8"

services:
  backend:
    image: ${REGISTRY_HOST:-registry.xsfire.com}/unstract/backend:${VERSION:-latest}
    build:
      context: ..
      dockerfile: backend/Dockerfile

  frontend:
    image: ${REGISTRY_HOST:-registry.xsfire.com}/unstract/frontend:${VERSION:-latest}
    build:
      context: ..
      dockerfile: frontend/Dockerfile

  platform-service:
    image: ${REGISTRY_HOST:-registry.xsfire.com}/unstract/platform-service:${VERSION:-latest}
    build:
      context: ..
      dockerfile: platform-service/Dockerfile

  prompt-service:
    image: ${REGISTRY_HOST:-registry.xsfire.com}/unstract/prompt-service:${VERSION:-latest}
    build:
      context: ..
      dockerfile: prompt-service/Dockerfile

  x2text-service:
    image: ${REGISTRY_HOST:-registry.xsfire.com}/unstract/x2text-service:${VERSION:-latest}
    build:
      context: ..
      dockerfile: x2text-service/Dockerfile

  runner:
    image: ${REGISTRY_HOST:-registry.xsfire.com}/unstract/runner:${VERSION:-latest}
    build:
      context: ..
      dockerfile: runner/Dockerfile

  worker-unified:
    image: ${REGISTRY_HOST:-registry.xsfire.com}/unstract/worker-unified:${VERSION:-latest}
    build:
      context: ..
      dockerfile: workers/unified/Dockerfile
